apiVersion: v1
kind: Service
metadata:
  name: whereismydriver
  labels:
    run: whereismydriver
spec:
  ports:
  -  port: 3001
     targetPort: 3001
     nodePort: 3000
     name: app
  type: LoadBalancer
  selector:
    run: whereismydriver